### ISSUE TITLE
Merge all failing workflows

### ISSUE THREAD

**Issue by fussel178** [wuespace/telestion#216]
1. Merge all failing CI workflows into working ones.
2. Set the `continue-on-error` flag to `true` on the specific step that can fail due permission errors, e.g. upload test report, annotations, etc.

See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error

The following repos need an update:

- [x] https://github.com/wuespace/telestion-core
- [x] https://github.com/wuespace/telestion-client
- [x] https://github.com/wuespace/telestion-terminal-client
- [x] https://github.com/wuespace/telestion-serial-connector
- [x] https://github.com/wuespace/telestion-project-template
- [x] https://github.com/wuespace/telestion-project-rocketsound
- [x] https://github.com/wuespace/telestion-project-daedalus2
- [x] https://github.com/wuespace/telestion-extension-template
- [x] https://github.com/wuespace/telestion-extension-mavlink
- [x] https://github.com/wuespace/telestion-extension-mongodb
- [x] https://github.com/wuespace/telestion-extension-matlab

**Comment by fussel178** [comment]
Or better, skip the steps which require permissions or tokens to work with:
```yml
      - name: Upload Test Report 📠
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: scacap/action-surefire-report@v1.0.13
```
